#!/usr/bin/python

import numpy as np
import csv
import math
import sys

H = np.loadtxt("/dev/stdin", delimiter=",")

def bin_size(x):
    return math.pow(10,math.floor(math.log10(x))-1)

p = sys.argv[1] if len(sys.argv) >= 2 else 1
for b,c in H:
    for _ in xrange(int(c)):
        if np.random.rand() < p:
            print b + np.random.uniform(low=b,high=b+bin_size(b))
